// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2N3ql8MHgyP0sn-ubv9Q2kf72qWntEE',
    appId: '1:771455183307:web:ff1d73a3a0096793886e4e',
    messagingSenderId: '771455183307',
    projectId: 'gardienvie-1fe1e',
    authDomain: 'gardienvie-1fe1e.firebaseapp.com',
    storageBucket: 'gardienvie-1fe1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRl5ZbsFdm3ropf9X2v2SvSndGuYjMxq4',
    appId: '1:771455183307:android:59e26f015372364a886e4e',
    messagingSenderId: '771455183307',
    projectId: 'gardienvie-1fe1e',
    storageBucket: 'gardienvie-1fe1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8ZT67S1xM3SMfco7Mo6iisj3Hvu3Mlo',
    appId: '1:771455183307:ios:03384e03538cbc2e886e4e',
    messagingSenderId: '771455183307',
    projectId: 'gardienvie-1fe1e',
    storageBucket: 'gardienvie-1fe1e.appspot.com',
    iosBundleId: 'com.example.gardienvie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8ZT67S1xM3SMfco7Mo6iisj3Hvu3Mlo',
    appId: '1:771455183307:ios:e0b655d13615e885886e4e',
    messagingSenderId: '771455183307',
    projectId: 'gardienvie-1fe1e',
    storageBucket: 'gardienvie-1fe1e.appspot.com',
    iosBundleId: 'com.example.gardienvie.RunnerTests',
  );
}
